# Generated by Django 6.0 on 2025-12-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoja', '0004_remove_product_farmer_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payhero_reference',
            field=models.CharField(blank=True, help_text='Payhero external reference for tracking', max_length=255, null=True),
        ),
    ]
